### ISSUE TITLE
[BUG] App Reloads Multiple Times Instead of Once When Auto-Reload is Enabled

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/tkreload#12] opened 2024-10-23 06:23 UTC
**Describe the bug**
In the demo GIF, the app reloads three times, whereas it should only reload once. This issue occurs specifically when auto-reload is enabled and needs to be addressed.

**To Reproduce**
1. Enable auto-reload.
2. Make changes to `sample_app.py` while running it using `tkreload`.

**Expected behavior**
The app should reload only once for each change, rather than three times.

**Screenshots**
![With tkreload](https://github.com/iamDyeus/tkreload/blob/main/.assets/with.gif?raw=true)

**Additional context**
It might be worth increasing the time buffer after which file changes are monitored in main.py. Also, ensure that the relevant tests are updated accordingly after fixing this issue.

**Comment by hriteshMaikap** [comment] 2024-10-23 06:47
Hey! I tried to reproduce the bug. I have installed the dependcies as well.
After running the following command:
`tkreload example/sample_app.py`

I get the app running and the following output is displayed. 
 Tkreload is running ✅
        - Press H for help,
        - R to restart,
        - A to toggle auto-reload (currently Enabled),
        - Ctrl + C to exit.
        
But when I make any change in the sample_app.py, I don't see the file reloading. Can you please elaborate where I may be wrong? 
Once I reproduce this error I think I can fix this bug.

**Comment by iamDyeus** [comment] 2024-10-23 15:47
Make sure you pass the Tkinter app file to TkReload:

`tkreload sample_app.py`

Additionally, ensure Autosave is enabled in your code editor. Otherwise, you'll need to manually save your changes so that the module can detect file modifications and reload the application.(As shown in the GIF above, you can see how it works.)

If you're still having trouble running it, feel free to message me, and I'll send you a video tutorial to help you reproduce the error.

**Comment by hriteshMaikap** [comment] 2024-10-24 08:04
Thanks I have reproduced the issue, will work on it.

**Comment by iamDyeus** [comment] 2024-10-24 14:20
There were some slight changes made in recent commits. Please make sure to pull before pushing to avoid merge conflicts and failing tests.

**Comment by savsch** [comment] 2024-10-25 21:13
The issue looks interesting. Although the issue description says "three times", I found that the number of times the reload occurs depends on the editor.

The `on_modified` method of `app_event_handler.AppFileEventHandler` gets called multiple times leading to the "bug", when an editor saves the file.
This occurs when `FileModifiedEvent` fires multiple times and that's intended for watchdog, because the editor makes multiple writes to the file, even though it apparently "[auto ]saves" it  only once.

---

In my opinion, working around it will require a design choice to be made (whether to opt for checking whether file contents actually changed after the event fires (slow but robust), or issuing a cooldown (quick but unreliable and machine dependent), or some other alternative). @iamDyeus, which way do  you think will be the most viable?

**Comment by kartik-212004** [comment] 2024-10-26 13:09
I would like to resolve this issue. Please assign it to me.
Thanks

**Comment by iamDyeus** [comment] 2024-10-26 17:46
> The issue looks interesting. Although the issue description says "three times", I found that the number of times the reload occurs depends on the editor.
> 
> The `on_modified` method of `app_event_handler.AppFileEventHandler` gets called multiple times leading to the "bug", when an editor saves the file. This occurs when `FileModifiedEvent` fires multiple times and that's intended for watchdog, because the editor makes multiple writes to the file, even though it apparently "[auto ]saves" it only once.
> 
> In my opinion, working around it will require a design choice to be made (whether to opt for checking whether file contents actually changed after the event fires (slow but robust), or issuing a cooldown (quick but unreliable and machine dependent), or some other alternative). @iamDyeus, which way do you think will be the most viable?

Firstly, great observations! I think the module needs faster reloads when building user interfaces, as we often need to check the effects of small changes quickly. However, considering your perspective on this solution’s potential unreliability, I suggest we go with the first option you suggested _(slow but robust)_. But we could add a fast-reload command option too, allowing users to choose the best method based on different scenarios, this way we'll have both the suggestions available, each having its own benefits. 

I've also been reading some documentation recently and was thinking that we could implement something like component hot-reloading. This feature could potentially evolve into fast reloading in the future, I mentioned above.

**Comment by iamDyeus** [comment] 2024-10-26 17:49
> I would like to resolve this issue. Please assign it to me. Thanks

Let’s see if @savsch will be working on this, as he responded to the thread first. If not, the issue will be assigned to you. 😄

**Comment by savsch** [comment] 2024-10-27 12:48
> I've also been reading some documentation recently and was thinking that we could implement something like component hot-reloading. This feature could potentially evolve into fast reloading in the future, I mentioned above.

Yup, something akin to hot reloading will be great if possible.

---

> Let’s see if @savsch will be working on this

I can work on this. Going to implement a solution which computes the `app_file`'s hash to confirm changes. This should be reasonably fast for most files (unless the source file is unusually large e.g. 100s of MBs in size. Even then, it's other stuff like  the editor which is likely to affect user experience, and not the computing of the hash itself).

**Comment by iamDyeus** [comment] 2024-10-28 17:52
@savsch are you working on this issue?

**Comment by iamDyeus** [comment] 2024-10-30 12:22
> I would like to resolve this issue. Please assign it to me. Thanks

Hey @kartik-212004, I'll assign this issue to you if you're still interested in working on it!

**Comment by kartik-212004** [comment] 2024-10-31 05:51
@iamDyeus  i am interested to solve this issue, Thanks

**Comment by iamDyeus** [comment] 2024-11-05 18:09
@kartik-212004 any updates on this?

**Closed** 2024-11-19 06:06 UTC
Labels: bug, good first issue, intermediate
